- name: Creeating a repo file for Logstash (CentOS)
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d/logstash.repo
    owner: root
    group: root
    mode: 0777
  when: ansible_distribution == "CentOS"

- name: Creating a repo file for Logstash (Ubuntu)
  copy:
    src: logstash.repo
    dest: /etc/apt/sources.list.d/logstash.repo
    owner: root
    group: root
    mode: 0777
  when: ansible_distribution == "CentOS"

- name: Installing Logstash
  package:
    name: logstash
    state: latest

- name: Opening port for Logstash
  become: true
  shell: |
    firewall-cmd --permanent --zone=public --add-port=9600/tcp
    sleep 10
    firewall-cmd --reload

- name: Making sure that logstash is stared and enabled
  service:
    name: logstash
    state: restarted
    enabled: true
