---
#- hosts: all
#  become: true
#  tasks:
#  - name: Install Packages (Ubuntu)
#    apt: name= state=latest update_cache=yes
#    with_items:
#      - apt-transport-https
#      - openssl
#      - default-jdk
#    when: ansible_distribution == "Ubuntu"
#  - name: Install Packages (CentOS)
#    dnf: name= state=latest update_cache=yes
#    with_items:
#     - yum-utils
#     - openssl
#     - java-1.8.0-openjdk
#    when: ansible_distribution == "CentOS"

- hosts: elasticsearch
  tags: es
  become: true
  roles:
   - elasticsearch

 #- hosts: kibana
 #  tags: kibana
 #  become: true
 #  roles:
 #    - kibana

 #- hosts: logstash
 #  tags: logstash
 #  become: true
 #  roles:
 #    - logstash
